config/routes.rb
Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  devise_for :accounts, controllers: {
    omniauth_callbacks: "accounts/omniauth_callbacks"
  }

  resources :blocks
  resources :exemptions, only: [:create]
end

app/models/account.rb
class Account < ActiveRecord::Base
  devise :registerable
  devise :omniauthable, omniauth_providers: [:twitter]

  has_many :blocks, dependent: :destroy
  has_many :exemptions, dependent: :destroy

  default_scope  do
    order(:created_at)
  end

  validates :username, presence: true
  validates :external_id, presence: true
  validates :provider, presence: true
  validates :access_public, presence: true
  validates :access_private, presence: true

  def self.where_twitter(data)
    where(
      provider: data.provider,
      external_id: data.uid,
      username: data.info.nickname,
      access_public: data.credentials.token,
      access_private: data.credentials.secret
    )
  end
end

app/models/block.rb
class Block < ActiveRecord::Base
  belongs_to :account
  has_many :connections, dependent: :destroy

  default_scope  do
    order(:created_at)
  end

  attr_writer :username

  def trunk
    connections.trunk.profile
  end

  def leafs
    Profile.where(id: connections.leafs.pluck(:profile_id)).where.not(external_id: account.exemptions.pluck(:external_id))
  end

  def exemptions
    Profile.where(id: connections.leafs.pluck(:profile_id)).where(external_id: account.exemptions.pluck(:external_id))
  end
end

app/models/connection.rb
class Connection < ActiveRecord::Base
  belongs_to :block
  belongs_to :profile
  belongs_to :trunk, class_name: "Profile", foreign_key: "trunk_id"

  default_scope  do
    order(:created_at)
  end

  scope :leafs, -> do
    joins(:profile).where.not(trunk_id: nil)
  end

  def self.trunk
    joins(:profile).where(trunk_id: nil).first
  end

  scope :missing, ->(followers) do
    joins(:profile).where.not(profiles: { external_id: followers })
  end

  validates :block, presence: true
  validates :profile, presence: true
end

app/models/exemption.rb
class Exemption < ActiveRecord::Base
  belongs_to :account
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  acts_as_paranoid without_default_scope: true

  has_many :connections, dependent: :destroy

  validates :external_id, presence: true
  validates :provider, presence: true

  default_scope  do
    order(:created_at)
  end

  scope :twitter, -> do
    where(provider: "twitter")
  end
end

app/controllers/accounts/omniauth_callbacks_controller.rb
class Accounts::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @account = Account.where_twitter(request.env["omniauth.auth"]).first_or_create

    if @account.persisted?
      sign_in_and_redirect @account, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_account_registration_url
    end
  end


  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  def after_omniauth_failure_path_for(scope)
    new_account_registration_url
  end

  def after_sign_in_path_for(resource)
    blocks_url
  end
end

app/controllers/accounts/registrations_controller.rb
class Accounts::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :authenticate_account!

  def index
    @blocks = current_account.blocks
  end

  def show
    @block = current_account.blocks.find_by!(id: params[:id])
  end

  def new
    @block = Block.new
  end

  def create
    @block = current_account.blocks.create!
    username = params[:username].gsub("@", "")

    InitiateGraphWorker.perform_async(current_account.id, @block.id, username)

    redirect_to blocks_path
  end
end

app/controllers/exemptions_controller.rb
class ExemptionsController < ApplicationController
  before_action :authenticate_account!

  def create
    CreateExemptionWorker.perform_async(current_account.id, params[:id])

    redirect_to :back
  end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/index.html.erb
<h1>Blocks</h1>

<p>
  Block <%= link_to "here", new_block_path %>.
</p>

<p>
  Refresh this page liberally.
</p>

<ul>
  <% @blocks.each do |block| %>
    <li>
      <% if block.connections.trunk %>
        <%= link_to block.trunk.username, block_path(block) %>
      <% else %>
        <%= link_to "Processing...", block_path(block) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/blocks/new.html.erb
<h1>New Block</h1>

<%= form_tag("/blocks", method: :post) do %>
  <%= text_field_tag :username %>

  <%= submit_tag "Block" %>
<% end %>

app/views/blocks/show.html.erb
<h1>
  <% if @block.connections.trunk %>
    <%= @block.trunk.username %>
  <% else %>
    Pending block <%= @block.id %>
  <% end %>
</h1>

<% if @block.connections.trunk %>
  <section>
    <h1>Trunk</h1>

    <p>
      <% if @block.trunk.username %>
        <%= @block.trunk.username %>
      <% else %>
        Processing...
      <% end %>
      (<%= @block.trunk.provider %> / <%= @block.trunk.external_id %>)
    </p>
  </section>
<% else %>
  <p>
    Currently we haven't processed the trunk.
  </p>
<% end %>

<% if @block.leafs.any? %>
  <section>
    <h1>Leafs</h1>
    <ol>
      <% @block.leafs.each do |leaf| %>
        <li>
          <% if leaf.username %>
            <%= leaf.username %>
          <% else %>
            Processing...
          <% end %>
          <%= form_tag exemptions_path, method: :post, style: "display: inline;" do %>
            <%= hidden_field_tag :id, leaf.id %>
            <%= submit_tag "exempt" %>
          <% end %>
        </li>
      <% end %>
    </ol>
  </section>
<% else %>
  <p>
    Currently we haven't processed any leaf nodes.
  </p>
<% end %>
<% if @block.exemptions %>
  <section>
    <h1>Exemptions</h1>
    <ol>
      <% @block.exemptions.each do |leaf| %>
        <li>
          <% if leaf.username %>
            <%= leaf.username %>
          <% else %>
            Processing...
          <% end %>
        </li>
      <% end %>
    </ol>
  </section>
<% else %>
  <p>
    Currently we haven't processed any exemptions.
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blockgraph</title>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>